# this seems to be not useful at all
MAX_NUM_WORDS = 200000

MAX_ARTICLE_LENGTH = 512
MAX_SUMMARY_LENGTH = 128

ARTICLE_MAX_SENT = 10
SUMMARY_MAX_SENT = 3

EMBEDDING_DIM = 100

# VALIDATION_SPLIT = 0.2
